
2s
Run set(ENV{CC} gcc)
-- The CXX compiler identification is unknown
-- Check for working CXX compiler: C:/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/mingw64/bin/g++.exe -- broken
CMake Error at cmake-3.16.2-win64-x64/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "C:/mingw64/bin/g++.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/a/Computer-Graphics-Homework/Computer-Graphics-Homework/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):ninja cmTC_e0153 && [1/2] Building CXX object CMakeFiles\cmTC_e0153.dir\testCXXCompiler.cxx.obj
    FAILED: CMakeFiles/cmTC_e0153.dir/testCXXCompiler.cxx.obj 
    C:\mingw64\bin\g++.exe     -o CMakeFiles\cmTC_e0153.dir\testCXXCompiler.cxx.obj -c testCXXCompiler.cxx
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
See also "D:/a/Computer-Graphics-Homework/Computer-Graphics-Homework/build/CMakeFiles/CMakeOutput.log".
See also "D:/a/Computer-Graphics-Homework/Computer-Graphics-Homework/build/CMakeFiles/CMakeError.log".
CMake Error at D:/a/_temp/359cfc10-442a-42b4-b73e-57d0678dfe37:32 (message):
  Bad exit status


Error: Process completed with exit code 1.
Run set(ENV{CC} gcc)
-- The CXX compiler identification is unknown
-- Check for working CXX compiler: C:/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/mingw64/bin/g++.exe -- broken
CMake Error at cmake-3.16.2-win64-x64/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "C:/mingw64/bin/g++.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/a/Computer-Graphics-Homework/Computer-Graphics-Homework/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):ninja cmTC_e0153 && [1/2] Building CXX object CMakeFiles\cmTC_e0153.dir\testCXXCompiler.cxx.obj
    FAILED: CMakeFiles/cmTC_e0153.dir/testCXXCompiler.cxx.obj 
    C:\mingw64\bin\g++.exe     -o CMakeFiles\cmTC_e0153.dir\testCXXCompiler.cxx.obj -c testCXXCompiler.cxx
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
See also "D:/a/Computer-Graphics-Homework/Computer-Graphics-Homework/build/CMakeFiles/CMakeOutput.log".
See also "D:/a/Computer-Graphics-Homework/Computer-Graphics-Homework/build/CMakeFiles/CMakeError.log".
CMake Error at D:/a/_temp/359cfc10-442a-42b4-b73e-57d0678dfe37:32 (message):
  Bad exit status
